# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Sysdig - Build, scan, push and upload SARIF report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      checks: write
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        id: build
        run: |
          IMAGE_TAG=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')
          echo "image-tag=$IMAGE_TAG:latest" >> "$GITHUB_OUTPUT"
          docker build . --file Dockerfile --tag "$IMAGE_TAG:latest"

      - name: Sysdig Secure Inline Scan
        id: scan
        uses: sysdiglabs/scan-action@768d7626a14897e0948ea89c8437dd46a814b163
        with:
          image-tag: ${{ steps.build.outputs.image-tag }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: https://us2.app.sysdig.com
          dockerfile-path: ./Dockerfile
          input-type: docker-daemon
          ignore-failed-scan: true
          run-as-user: root

      - uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: ${{ steps.scan.outputs.sarifReport }}
